
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Apr 23 20:01:57 BRT 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FECHA_PAREN = 9;
  public static final int MAIS = 3;
  public static final int PTVIRG = 2;
  public static final int INTEIRO = 11;
  public static final int MENOS = 4;
  public static final int MULT = 6;
  public static final int MOD = 7;
  public static final int ERROR = 10;
  public static final int EOF = 0;
  public static final int ABRE_PAREN = 8;
  public static final int DIV = 5;
  public static final int error = 1;
}

